sudo: false
dist: trusty
language: c
compiler: gcc

jobs:
  include:
    - stage: Tests
      script: ./build.sh # TODO: Add smoke test
    - stage: Tag
      script: ./tag_version.sh
    - stage: GitHub release
      script: ./build.sh
      deploy: 
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file_glob: true
        file: ./build/libblockaccess.so.*
        skip_cleanup: true
        on:
          tags: true
            
    
  
