sudo: false
dist: trusty
language: c
compiler: gcc

jobs:
  include:
    - stage: Tests
      script: ./build.sh # TODO: Add smoke test
    - stage: GitHub release & deploy
      script: ./build.sh
      before_deploy: 
        - ./tag_version.sh
      deploy: 
        provider: releases
        api_key: $GH_TOKEN
        file_glob: true
        file: 
          - ./build/libblockaccess.so.*
          - ./build/testreader*
        skip_cleanup: true
            
    
  
