sudo: false
dist: trusty
language: c
compiler: gcc

jobs:
  include:
    - stage: GitHub release
      script: chmod +x ./build.sh && ./build.sh
      deploy: 
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file_glob: true
        file: ./build/libblockaccess.so.*
        skip_cleanup: true
        on:
          tags: true
            
    
  
