#ifndef FBAM_CONSTANTS_H
#define FBAM_CONSTANTS_H

#include <unistd.h>

#define TIMESTAMP_BUFFER_LEN 38

#define MAX_LOG_LEN (MAXPATHLEN + 50)
#define BUFFER_SIZE 100

#define HF_VAR_FS_MONIT_ENABLED "HF_VAR_FS_MONIT_ENABLED"
#define HF_VAR_FS_MONIT_COMMAND "HF_VAR_FS_MONIT_COMMAND"
#define HF_VAR_FS_MONIT_LOGFILE "HF_VAR_FS_MONIT_LOGFILE"
#define HF_VAR_FS_MONIT_PATH_FILTER "HF_VAR_FS_MONIT_PATH_FILTER"

#endif //FBAM_CONSTANTS_H
