#ifndef FBAM_CONSTANTS_H
#define FBAM_CONSTANTS_H

#include <unistd.h>

#define TIMESTAMP_BUFFER_LEN 19

#define MAX_LOG_LEN (MAXPATHLEN + 50)
#define BUFFER_SIZE 100

#define HF_FS_MONIT_ENABLED_ENV_VAR "HF_FS_MONIT_ENABLED"
#define HF_FS_MONIT_COMMAND_ENV_VAR "HF_FS_MONIT_COMMAND"
#define HF_FS_MONIT_LOGFILE_ENV_VAR "HF_FS_MONIT_LOGFILE"
#define HF_FS_MONIT_PATH_FILTER_ENV_VAR "HF_FS_MONIT_PATH_FILTER"

#endif //FBAM_CONSTANTS_H
